---
apiVersion: v1
kind: ConfigMap
metadata:
  name: currencyservice-config
data:
  PORT: "7000"
  DISABLE_PROFILER: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shippingservice-config
data:
  PORT: "50051"
  DISABLE_PROFILER: "1"
